### ISSUE TITLE
Not compatible with ovos_utils v0.12a1

### ISSUE THREAD

**Issue by theCalcaholic** [JarbasSkills/skill-old-world-radio#2]
Apparently, there is no module `ovos_utils.skills.templates` in the latest release of ovos_utils.
See also https://github.com/JarbasSkills/skill-sovietwave/issues/2

Stack Trace:

```
mycroft.skills.skill_loader:_load_skill_source:278 | Failed to load skill: skill-old-world-radio.jarbasskills (ModuleNotFoundError("No module named 'ovos_utils.skills.templates'"))
Traceback (most recent call last):
  File "/home/neon/bigscreen-build/mycroft-core/mycroft/skills/skill_loader.py", line 276, in _load_skill_source
    skill_module = load_skill_module(main_file_path, self.skill_id)
  File "/home/neon/bigscreen-build/mycroft-core/mycroft/skills/skill_loader.py", line 72, in load_skill_module
    spec.loader.exec_module(mod)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/mycroft/skills/skill-old-world-radio.jarbasskills/__init__.py", line 1, in <module>
    from ovos_utils.skills.templates.common_play import BetterCommonPlaySkill
```

**Comment by JarbasAl** [comment]
this functionality has been migrated from ovos_utils to https://github.com/OpenVoiceOS/OVOS-workshop

this skill also needs to be updated as the original streams went down

**Comment by JarbasAl** [comment]
fixed imports and updated streams
